{{- if values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm-01
  namespace: chart
  labels:
    app: nginx-helm-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-helm-01
  template:
    metadata:
      labels:
        app: nginx-helm-01
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: svc-nginx-helm-01
  name: svc-nginx-helm-01
  namespace: chart
spec:
  ports:
  - name: http
    port: 8808
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-helm-01
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm-02
  namespace: chart
  labels:
    app: nginx-helm-02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-helm-02
  template:
    metadata:
      labels:
        app: nginx-helm-02
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: svc-nginx-helm-02
  name: svc-nginx-helm-02
  namespace: chart
spec:
  ports:
  - name: http
    port: 8800
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-helm-02
  type: ClusterIP
