{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}-deploy-dev
  labels:
    name: dkong
    app: dkong
  namespace: apache
spec:
  {{- if .Values.deployment.replicas.enabled }}
  replicas: {{ .Values.deployment.replicas.replicas }}
  else replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      name: pod
      labels:
        app: kong
      namespace: apache
    spec:
      containers:
        - name: cpod
          image: nginx
{{- end }}          
    
