apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    name: dkong
    app: dkong
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      name: pod
      labels:
        app: kong
      namespace: apache
    spec:
      containers:
        - name: cpod
          image: nginx
          
    
