apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    name: php
    app: php
  namespace: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      name: php-pod
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: nginx
        ports:
        - name: php-port
          containerPort: 80
          protocol: TCP

