apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    name: kong
    app: kong
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong
  metadata:

  templates:
    
