apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    app: apache
    env: dev
  namespace: apache
spec:
  containers:
  - name: apache
    image: httpd
    ports:
    - name: http
      protocol: TCP
      containerPort: 8080
