# Create Storage class with retain policy
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "{{ template "kong.fullname" . }}"
  namespace:  {{ template "kong.namespace" . }}
provisioner: "{{ template "kong.provisioner" . }}"
allowVolumeExpansion: "{{ template "kong.Expansion" . }}"
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: "{{ template "kong.skuName" . }}"
